<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Tasmaniski API</title>
    <link rel="icon" type="image/png" href="<?php echo $this->basePath('swagger-ui/images/logo_small.png'); ?>" sizes="32x32" />
    <link rel="icon" type="image/png" href="<?php echo $this->basePath('swagger-ui/images/logo_small.png'); ?>" sizes="16x16" />

    <link href='<?php echo $this->basePath('swagger-ui/css/typography.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/reset.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/screen.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/reset.css'); ?>' media='print' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/print.css'); ?>' media='print' rel='stylesheet' type='text/css'/>

    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery-1.8.0.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.slideto.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.wiggle.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.ba-bbq.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/handlebars-2.0.0.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/underscore-min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/backbone-min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/swagger-ui.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/highlight.7.3.pack.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jsoneditor.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/marked.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/swagger-oauth.js'); ?>' type='text/javascript'></script>

    <script type="text/javascript">
        $(function () {
            var url = "<?php echo $this->basePath($this->swaggerUrl); ?>";

            window.swaggerUi = new SwaggerUi({
                url: url,
                dom_id: "swagger-ui-container",
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
                onComplete: function (swaggerApi, swaggerUi) {
                    $('pre code').each(function (i, e) {
                        hljs.highlightBlock(e)
                    });

                    $(".endpoints").css("display", "block");
                },
                onFailure: function (data) {
                    console.log("Unable to Load SwaggerUI");
                },
                docExpansion: "none",
                jsonEditor: false,
                apisSorter: "alpha",
                defaultModelRendering: 'schema',
                showRequestHeaders: false,
                validatorUrl: null
            });

            function addApiKeyAuthorization() {
              var apitoken = $('#api_token').val() && $('#api_token')[0].value;
              if (apitoken && apitoken.trim() != "") {
                var apitokenKey = new SwaggerClient.ApiKeyAuthorization("Authorization", 'Bearer ' + apitoken, "header");
                window.swaggerUi.api.clientAuthorizations.add("Authorization", apitokenKey);
              }
            }

            $('#api_token').keyup(addApiKeyAuthorization);
            $(document).on('click', '.submit', addApiKeyAuthorization);

            window.swaggerUi.load();
        });
    </script>

</head>

<body class="swagger-section">
<div id='header'>
    <div class="swagger-ui-wrap">
        <a id="logo" href="<?php echo $this->url('swagger-ui'); ?>">Tasmaniski</a>
    </div>
</div>

<div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
<br/><br/><br/><br/>
</body>
</html>