<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Golive API</title>
    <link rel="icon" type="image/png" href="<?php echo $this->basePath('swagger-ui/images/logo_small.png'); ?>" sizes="32x32" />
    <link rel="icon" type="image/png" href="<?php echo $this->basePath('swagger-ui/images/logo_small.png'); ?>" sizes="16x16" />

    <link href='<?php echo $this->basePath('swagger-ui/css/typography.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/reset.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/screen.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/reset.css'); ?>' media='print' rel='stylesheet' type='text/css'/>
    <link href='<?php echo $this->basePath('swagger-ui/css/print.css'); ?>' media='print' rel='stylesheet' type='text/css'/>

    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery-1.8.0.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.slideto.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.wiggle.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.ba-bbq.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/handlebars-2.0.0.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/underscore-min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/backbone-min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/swagger-ui.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/highlight.7.3.pack.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/jsoneditor.min.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/marked.js'); ?>' type='text/javascript'></script>
    <script src='<?php echo $this->basePath('swagger-ui/lib/swagger-oauth.js'); ?>' type='text/javascript'></script>

    <script type="text/javascript">
        $(function () {
            var url = "<?php echo $this->basePath($this->swaggerUrl); ?>";

            window.swaggerUi = new SwaggerUi({
                url: url,
                dom_id: "swagger-ui-container",
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
                onComplete: function (swaggerApi, swaggerUi) {
                    $('pre code').each(function (i, e) {
                        hljs.highlightBlock(e)
                    });

                    addApiKeyAuthorization();

                    $(".endpoints").css("display", "block");
                },
                onFailure: function (data) {
                    console.log("Unable to Load SwaggerUI");
                },
                docExpansion: "none",
                jsonEditor: false,
                apisSorter: "alpha",
                defaultModelRendering: 'schema',
                showRequestHeaders: false,
                validatorUrl: null
            });

            function addApiKeyAuthorization() {
                var key = $('#input_apiKey')[0].value;
                if (key && key.trim() != "") {
                    var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", key, "header");
                    window.swaggerUi.api.clientAuthorizations.add("Authorization", apiKeyAuth);
                }

                var mcc = $('#input_mcc')[0].value;
                if (mcc && mcc.trim() != "") {
                    var mccKey = new SwaggerClient.ApiKeyAuthorization("mcc", mcc, "header");
                    window.swaggerUi.api.clientAuthorizations.add("mcc", mccKey);
                }

                var mnc = $('#input_mnc')[0].value;
                if (mnc && mnc.trim() != "") {
                    var mncKey = new SwaggerClient.ApiKeyAuthorization("mnc", mnc, "header");
                    window.swaggerUi.api.clientAuthorizations.add("mnc", mncKey);
                }

                var xforward = $('#input_xforward')[0].value;
                if (xforward && xforward.trim() != "") {
                    var xforwardKey = new SwaggerClient.ApiKeyAuthorization("X-Forwarded-For", xforward, "header");
                    window.swaggerUi.api.clientAuthorizations.add("X-Forwarded-For", xforwardKey);
                }

                var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Auth", 'Basic <?php echo base64_encode('IC6JEm9rMymnNXewq2cISQs0X:v1f8ugyDmlmIIx1xmhIfgHuTY') ?>', "header");
                window.swaggerUi.api.clientAuthorizations.add("Auth", apiKeyAuth);
            }

            $('#input_apiKey, #input_mcc, #input_mnc, #input_xforward').change(addApiKeyAuthorization);
            window.swaggerUi.load();
        });
    </script>

</head>

<body class="swagger-section">
<div id='header'>
    <div class="swagger-ui-wrap">
        <a id="logo" href="<?php echo $this->url('swagger-ui'); ?>">Golive</a>
        <form id='api_selector'>
            <div class='input'><input value="" style="width: 150px" placeholder="Add Bearer token" id="input_apiKey" name="apiKey" type="text"/></div>
            <div class='input'><input style="width: 150px" placeholder="Add MCC" id="input_mcc" name="mcc" type="text"/></div>
            <div class='input'><input style="width: 150px" placeholder="Add MNC" id="input_mnc" name="mnc" type="text"/></div>
            <div class='input'><input style="width: 150px" placeholder="Add X-Forwarded-For" id="input_xforward" name="xforward" type="text"/></div>
        </form>
    </div>
</div>

<div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
<br/><br/><br/><br/>
</body>
</html>